unique_ids:
  assets:
    standard-page.html: RDLMNMEEWJO5VM4APNQEIYXHM46PQ3IY
    theme.css: 52IVB2X4N5T25HYPBQT2326LUKF5VR44
  forms:
    Form1: ZAAGDUENBBDBPP6OJMLYACIRAPVJ4Z3H
  modules: {}
  scripts: {}
  server_modules:
    api_endpoints: EMIS6HY6OKXM3YEE7HWH4NZYXJXU6LJJ
    generation: IFWVDOPISZFJKEQPVNQZT7CX5KXRKIQC
    prompts: 5KOYPWCLV3BISNQ7M5COSX2PWMOLJYU6
    retrieval: YBJSZ7HDZ7DAA4OPWAPEHPXY7XX3VS54
    utils: NBRXGAABZP5IQ6WGSGHVNTUK3XXNUO62
